package View;

import Repository.LoginRegisterRepositoryImp;
import Service.LoginRegisterServiceImp;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author rian yuliawan
 */
public class LoginRegister extends javax.swing.JFrame {
    

    /**
     * Creates new form LoginRegister
     */
    
        private LoginRegisterServiceImp loginRegisterServiceImp;
    public LoginRegister() {
        initComponents();
           loginRegisterServiceImp = new LoginRegisterServiceImp
        (new LoginRegisterRepositoryImp());
        btnLogin.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String username = fieldusernameLogin.getText();
                String password = String.valueOf
                                (fieldPasswordLogin.getPassword());

                try {
                    if (username.isEmpty()) {
                        throw new IllegalArgumentException("Username not Blank");
                    } else if (password.isEmpty()) {
                        throw new IllegalArgumentException("Password not Blank");
                    }

                    loginRegisterServiceImp.loginService(username, password);


                    JFrame frame = new JFrame("TodoList");
                    frame.setContentPane(new Todolist().getJpaneTodo());
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.pack();
                    frame.setVisible(true);

                    JFrame loginFrame = (JFrame) SwingUtilities.getRoot(btnLogin);
                    loginFrame.dispose();
                } catch (IllegalArgumentException exception) {
                    JOptionPane.showMessageDialog
                    (null, exception.getMessage());
                } catch (RuntimeException exception) {
                    JOptionPane.showMessageDialog
                    (null, "Login failed: " + exception.getMessage());
                }
            }
        });

        btnRegister.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String username = fieldUsernameRegister.getText();
                String password = String.valueOf
                    (fieldPasswordRegister.getPassword());
                String passwordRepeat = String.valueOf
                    (fieldRePasswordRegister.getPassword());


                try {
                    if (username.isEmpty()) {
                        throw new IllegalArgumentException("Username not Blank");
                    } else if (password.isEmpty()) {
                        throw new IllegalArgumentException("Password not Blank");
                    } else if (!password.equals(passwordRepeat)) {
                        throw new IllegalArgumentException("Password not match");
                    }

                    loginRegisterServiceImp.registerUser
                                (new Entity.LoginRegister(username,password));
                    JOptionPane.showMessageDialog
                                (null, "Register successfully");
                    fieldUsernameRegister.setText("");
                    fieldPasswordRegister.setText("");
                    fieldRePasswordRegister.setText("");
                } catch (RuntimeException exception) {
                    JOptionPane.showMessageDialog(null, 
                                "Register failed: " + exception.getMessage());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelLoginRegister = new javax.swing.JPanel();
        background2 = new login.Background();
        Login = new javax.swing.JPanel();
        fieldusernameLogin = new swing.TextField();
        fieldPasswordLogin = new swing.PasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnShowPasswordLogin = new swing.buttonTransparant();
        btnLogin = new swing.Button();
        background11 = new login.Background1();
        Register = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldUsernameRegister = new swing.TextField();
        fieldPasswordRegister = new swing.PasswordField();
        fieldRePasswordRegister = new swing.PasswordField();
        btnRegister = new swing.Button();
        btnShowPasswordReg = new swing.buttonTransparant();
        btnShowPasswordReReg = new swing.buttonTransparant();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background2.setBlur(Login);

        Login.setOpaque(false);

        fieldusernameLogin.setForeground(new java.awt.Color(102, 102, 102));
        fieldusernameLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        fieldusernameLogin.setHint("UserName");
        fieldusernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldusernameLoginActionPerformed(evt);
            }
        });

        fieldPasswordLogin.setForeground(new java.awt.Color(102, 102, 102));
        fieldPasswordLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        fieldPasswordLogin.setHint("Password");

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("LOGIN");

        btnShowPasswordLogin.setForeground(new java.awt.Color(102, 102, 102));
        btnShowPasswordLogin.setText("show");
        btnShowPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPasswordLoginActionPerformed(evt);
            }
        });

        btnLogin.setForeground(new java.awt.Color(102, 102, 102));
        btnLogin.setText("Sign In");
        btnLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldusernameLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(fieldPasswordLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(fieldusernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        background2.add(Login);
        Login.setBounds(60, 110, 360, 390);

        background11.setBlur(Register);

        Register.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("REGISTER");

        fieldUsernameRegister.setForeground(new java.awt.Color(102, 102, 102));
        fieldUsernameRegister.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldUsernameRegister.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        fieldUsernameRegister.setHint("UserName");
        fieldUsernameRegister.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        fieldUsernameRegister.setSelectionColor(new java.awt.Color(204, 204, 204));

        fieldPasswordRegister.setForeground(new java.awt.Color(102, 102, 102));
        fieldPasswordRegister.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        fieldPasswordRegister.setHint("Password");

        fieldRePasswordRegister.setForeground(new java.awt.Color(102, 102, 102));
        fieldRePasswordRegister.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        fieldRePasswordRegister.setHint("Repeat Password");
        fieldRePasswordRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRePasswordRegisterActionPerformed(evt);
            }
        });

        btnRegister.setForeground(new java.awt.Color(102, 102, 102));
        btnRegister.setText("Register");
        btnRegister.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnShowPasswordReg.setForeground(new java.awt.Color(102, 102, 102));
        btnShowPasswordReg.setText("show");
        btnShowPasswordReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPasswordRegActionPerformed(evt);
            }
        });

        btnShowPasswordReReg.setForeground(new java.awt.Color(102, 102, 102));
        btnShowPasswordReReg.setText("show");
        btnShowPasswordReReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPasswordReRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPasswordRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(fieldUsernameRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(fieldRePasswordRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowPasswordReg, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btnShowPasswordReReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(fieldUsernameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPasswordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRePasswordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowPasswordReReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        background11.add(Register);
        Register.setBounds(70, 120, 360, 390);

        javax.swing.GroupLayout jpanelLoginRegisterLayout = new javax.swing.GroupLayout(jpanelLoginRegister);
        jpanelLoginRegister.setLayout(jpanelLoginRegisterLayout);
        jpanelLoginRegisterLayout.setHorizontalGroup(
            jpanelLoginRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLoginRegisterLayout.createSequentialGroup()
                .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(background11, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpanelLoginRegisterLayout.setVerticalGroup(
            jpanelLoginRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(background11, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelLoginRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelLoginRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldRePasswordRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRePasswordRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRePasswordRegisterActionPerformed

    private void fieldusernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldusernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldusernameLoginActionPerformed

    private void btnShowPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPasswordLoginActionPerformed
         if (fieldPasswordLogin.getEchoChar() == '\u0000') {
        fieldPasswordLogin.setEchoChar('\u2022'); 
    } else {
        fieldPasswordLogin.setEchoChar((char) 0);
    }
    }//GEN-LAST:event_btnShowPasswordLoginActionPerformed

    private void btnShowPasswordRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPasswordRegActionPerformed
        if (fieldPasswordRegister.getEchoChar() == '\u0000') {
        fieldPasswordRegister.setEchoChar('\u2022'); 
    } else {
        fieldPasswordRegister.setEchoChar((char) 0);
    }             
    }//GEN-LAST:event_btnShowPasswordRegActionPerformed

    private void btnShowPasswordReRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPasswordReRegActionPerformed
        if (fieldRePasswordRegister.getEchoChar() == '\u0000') {
        fieldRePasswordRegister.setEchoChar('\u2022'); 
    } else {
        fieldRePasswordRegister.setEchoChar((char) 0);
    }               
    }//GEN-LAST:event_btnShowPasswordReRegActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private login.Background1 background11;
    private login.Background background2;
    private swing.Button btnLogin;
    private swing.Button btnRegister;
    private swing.buttonTransparant btnShowPasswordLogin;
    private swing.buttonTransparant btnShowPasswordReReg;
    private swing.buttonTransparant btnShowPasswordReg;
    private swing.PasswordField fieldPasswordLogin;
    private swing.PasswordField fieldPasswordRegister;
    private swing.PasswordField fieldRePasswordRegister;
    private swing.TextField fieldUsernameRegister;
    private swing.TextField fieldusernameLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpanelLoginRegister;
    // End of variables declaration//GEN-END:variables
}
